'use strict';
const keeperSet = new Set(Object.values(KEEPERS).flat().map(normalize));
const STORAGE_KEY = 'the-board-v1';
const defaultState = { drafted: [], slot: 8, teams: [...BASE_TEAMS] };
let state = loadState();
function normalize(s){return String(s||'').replace(/[QDO]$/,'').replace(/\s+/g,' ').trim().toLowerCase()}
function loadState(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));return saved&&Array.isArray(saved.drafted)?saved:{...defaultState}}catch(e){return {...defaultState}}}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}
function draftOrderAt(index){const round=Math.floor(index/10),within=index%10;return round%2===0?state.teams[within]:state.teams[9-within]}
function currentTeam(){return draftOrderAt(state.drafted.length)}
function available(){const drafted=new Set(state.drafted.map(x=>normalize(x.name)));return PLAYERS.filter(p=>!keeperSet.has(normalize(p.name))&&!drafted.has(normalize(p.name)))}
function ranked(){return available().slice().sort((a,b)=>(b.score-a.score)||(b.proj-a.proj))}
function showToast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>el.classList.remove('show'),1600)}
function draftPlayer(name){const p=PLAYERS.find(x=>x.name===name);if(!p)return;const team=currentTeam();state.drafted.push({...p,draftedBy:team,pick:state.drafted.length+1});save();render();showToast(`${p.name} drafted by ${team}`)}
function undo(){const p=state.drafted.pop();if(p){save();render();showToast(`Undid ${p.name}`)}}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function playerCard(p,i,compact=false){return `<div class="${compact?'mini-player':'player-card'}"><div class="rank">${i+1}</div><div><div class="player-name">${p.name}</div><div class="player-meta">${p.team} · ${p.pos} · ${p.tier}</div></div><div class="score projection">${Math.round(p.proj)}</div><button class="draft-btn" data-draft="${encodeURIComponent(p.name)}">${compact?'+':'Draft'}</button></div>`}
function renderRecommendation(list){const p=list[0],el=document.getElementById('recommend');if(!p){el.innerHTML='<div class="empty">Draft complete.</div>';return}el.innerHTML=`<div class="hero"><div class="pos-badge">${p.pos}</div><div><h2>${p.name}</h2><div class="muted">${p.team} · ${p.tier} tier</div></div></div><div class="metrics"><div class="metric"><b>${p.score}</b><span>BOARD SCORE</span></div><div class="metric"><b>${Math.round(p.proj)}</b><span>PROJECTED PTS</span></div><div class="metric"><b>${p.fit}</b><span>BUTCHER FIT</span></div><div class="metric"><b>${p.risk}</b><span>RISK</span></div></div><p class="why">${p.note}</p><div class="actions"><button class="btn primary" data-draft="${encodeURIComponent(p.name)}">Draft ${p.name}</button><button class="btn secondary" data-jump="board">View Board</button></div>`}
function renderRoster(){const all=[...KEEPERS['The Butcher'].map(name=>{const p=PLAYERS.find(x=>normalize(x.name)===normalize(name));return {name,pos:p?.pos||'—',keeper:true}}),...state.drafted.filter(x=>x.draftedBy==='The Butcher')];document.getElementById('myRoster').innerHTML=all.map(x=>`<div class="roster-row"><b>${x.pos}</b><span>${x.name}</span><span class="keeper-label">${x.keeper?'KEEPER':`PICK ${x.pick}`}</span></div>`).join('')}
function renderBoard(){const q=document.getElementById('boardSearch').value.toLowerCase(),pos=document.getElementById('boardPos').value;const arr=ranked().filter(p=>(pos==='ALL'||p.pos===pos)&&(`${p.name} ${p.team}`.toLowerCase().includes(q))).slice(0,50);document.getElementById('availableCount').textContent=`${available().length} available`;document.getElementById('boardTable').innerHTML=arr.length?arr.map((p,i)=>playerCard(p,i)).join(''):'<div class="empty">No players found.</div>'}
function renderLeague(){document.getElementById('rosters').innerHTML=state.teams.map(team=>{const keepers=KEEPERS[team]||[],drafted=state.drafted.filter(x=>x.draftedBy===team);return `<div class="team-card ${team==='The Butcher'?'me':''}"><h3>${team}</h3>${keepers.map(name=>{const p=PLAYERS.find(x=>normalize(x.name)===normalize(name));return `<div class="team-player"><span>${name}</span><b>${p?.pos||''} K</b></div>`}).join('')}${drafted.map(p=>`<div class="team-player"><span>${p.name}</span><b>${p.pos} #${p.pick}</b></div>`).join('')}</div>`}).join('')}
function renderHistory(){const el=document.getElementById('draftHistory');el.innerHTML=state.drafted.length?state.drafted.map(x=>`<div class="history-row"><b>#${x.pick}</b><span><strong>${x.name}</strong><br><small class="muted">${x.pos} · ${x.team}</small></span><span>${x.draftedBy}</span></div>`).join(''):'<div class="empty">No picks yet.</div>'}
function render(){const pick=state.drafted.length+1,list=ranked();document.getElementById('clockTeam').textContent=currentTeam();document.getElementById('clockPick').textContent=`Round ${Math.ceil(pick/10)} · Pick ${pick}`;document.getElementById('pickBadge').textContent=pick;renderRecommendation(list);document.getElementById('nextFive').innerHTML=list.slice(1,6).map((p,i)=>playerCard(p,i+1,true)).join('');renderRoster();renderBoard();renderLeague();renderHistory()}
function populateSlots(){const s=document.getElementById('slotSelect');s.innerHTML=Array.from({length:10},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('');s.value=state.slot}
function openSettings(){populateSlots();document.getElementById('settingsModal').hidden=false}
function closeSettings(){document.getElementById('settingsModal').hidden=true}
function applySlot(){const slot=Number(document.getElementById('slotSelect').value);const others=BASE_TEAMS.filter(t=>t!=='The Butcher');others.splice(slot-1,0,'The Butcher');state.slot=slot;state.teams=others;save();closeSettings();render();showToast(`Draft slot changed to ${slot}`)}
document.addEventListener('click',e=>{const draft=e.target.closest('[data-draft]');if(draft){draftPlayer(decodeURIComponent(draft.dataset.draft));return}const jump=e.target.closest('[data-jump]');if(jump){showView(jump.dataset.jump);return}const tab=e.target.closest('.tab');if(tab){showView(tab.dataset.view)}});
document.getElementById('boardSearch').addEventListener('input',renderBoard);document.getElementById('boardPos').addEventListener('change',renderBoard);document.getElementById('undoBtn').addEventListener('click',undo);document.getElementById('settingsBtn').addEventListener('click',openSettings);document.getElementById('closeSettings').addEventListener('click',closeSettings);document.getElementById('saveSettings').addEventListener('click',applySlot);document.getElementById('settingsModal').addEventListener('click',e=>{if(e.target.id==='settingsModal')closeSettings()});document.getElementById('resetBtn').addEventListener('click',()=>{if(confirm('Reset every drafted player? Keepers remain.')){state.drafted=[];save();closeSettings();render();showToast('Draft reset')}});
render();
