'use strict';
(function(){
  const VERSION='cockpit-v3.1.0';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const teamName=()=>window.state?.profile?.teamName||'The Butcher';
  const teamCount=()=>Math.max(1,Number(window.state?.profile?.teamCount||10));
  const drafted=()=>window.state?.drafted||[];
  const keepers=()=>window.state?.keepers||window.state?.profile?.keepers||[];
  const ranked=()=>{try{return window.ranked?.()||[]}catch{return[]}};
  const ownerAt=i=>{try{return window.draftOrderAt?.(i)||'League'}catch{return'League'}};
  const nameOf=p=>p?.name||p?.fullName||p?.player_name||'Open';
  const posOf=p=>String(p?.pos||p?.position||'').toUpperCase()||'—';
  const teamOf=p=>p?.team||p?.nflTeam||p?.pro_team||'—';
  const byeOf=p=>p?.bye??p?.byeWeek??p?.bye_week??'—';
  const photoOf=p=>p?.photo||p?.image||p?.headshot||p?.avatar||p?.img||p?.photoUrl||p?.imageUrl||p?.headshot_url||'';
  const initials=n=>String(n||'').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'—';
  const pickLabel=i=>`${Math.floor(i/teamCount())+1}.${String((i%teamCount())+1).padStart(2,'0')}`;
  const splitName=n=>{const a=String(n||'Open').trim().split(/\s+/);return[a.shift()||'Open',a.join(' ')]};
  const playerAt=i=>i<drafted().length?(drafted()[i]?.player||drafted()[i]||null):ranked()[i-drafted().length]||null;
  function photo(p,cls=''){const n=nameOf(p),src=photoOf(p);return `<span class="tbv31-photo ${cls}">${src?`<img src="${esc(src)}" alt="${esc(n)}" onerror="this.remove();this.nextElementSibling.hidden=false"><b hidden>${esc(initials(n))}</b>`:`<b>${esc(initials(n))}</b>`}</span>`}
  function stacked(p){const[f,l]=splitName(nameOf(p));return `<b class="tbv31-name"><span>${esc(f)}</span>${l?`<span>${esc(l)}</span>`:''}</b>`}
  function card(p,{pick='',owner='',status='',score='',state=''}={}){const pos=posOf(p).toLowerCase();return `<article class="tbv31-card pos-${esc(pos)} ${esc(state)}" data-player="${encodeURIComponent(nameOf(p))}"><header><span>${esc(posOf(p))}</span>${pick?`<small>${esc(pick)}</small>`:''}${score?`<strong>${esc(score)}</strong>`:''}</header><main>${photo(p,'tbv31-card-photo')}<div>${owner?`<small>${esc(owner)}</small>`:''}${stacked(p)}<em>${esc(teamOf(p))} · BYE ${esc(byeOf(p))}</em></div></main>${status?`<footer>${esc(status)}</footer>`:''}</article>`}
  function projectedRail(){const start=drafted().length;return `<section class="tbv31-projected"><div class="tbv31-projected-track">${Array.from({length:10},(_,n)=>{const idx=start+n,p=playerAt(idx),owner=ownerAt(idx),mine=owner===teamName();return card(p,{pick:pickLabel(idx),owner,status:n===0?'ON THE CLOCK':mine?'YOUR PICK':'PROJECTED',state:n===0?'is-current':mine?'is-yours':''})}).join('')}</div></section>`}
  function openSettings(){const modal=document.getElementById('settingsModal');if(!modal)return;modal.hidden=false;modal.removeAttribute('hidden');document.body.classList.add('modal-open');const input=document.getElementById('teamNamesInput');if(input){const label=input.closest('label');if(label){label.childNodes[0].textContent='Draft order ';const small=label.querySelector('small');if(small)small.textContent='One team per line, in exact selection order'}}}
  function renderBoard(){const board=document.getElementById('board');if(!board)return;const teams=Array.from({length:teamCount()},(_,i)=>ownerAt(i));const keeperList=Array.isArray(keepers())?keepers():[];const keeperMap=new Map();keeperList.forEach(k=>{const owner=k?.owner||k?.team||k?.teamName||'';if(!keeperMap.has(owner))keeperMap.set(owner,[]);keeperMap.get(owner).push(k?.player||k)});const rounds=Math.max(8,Math.ceil(Math.max(drafted().length,teamCount()*8)/teamCount()));const cells=[];for(let r=0;r<rounds;r++)for(let c=0;c<teamCount();c++){const idx=r*teamCount()+c,pick=drafted()[idx],p=pick?.player||pick||null;cells.push(`<article class="tbv31-board-pick ${p?'is-filled':''}"><small>${esc(pickLabel(idx))}</small>${p?`${photo(p,'tbv31-board-photo')}<div>${stacked(p)}<span>${esc(posOf(p))} · ${esc(teamOf(p))}</span></div>`:'<em>Open</em>'}</article>`)}board.innerHTML=`<section class="tbv31-board-shell"><header><div><small>LIVE DRAFT</small><h2>THE BOARD</h2></div><span>${drafted().length} picks made</span></header><div class="tbv31-board-teams">${teams.map(t=>`<div><b title="${esc(t)}">${esc(t)}</b>${(keeperMap.get(t)||[]).slice(0,5).map(p=>`<small>KEEPER · ${esc(nameOf(p))}</small>`).join('')}</div>`).join('')}</div><div class="tbv31-board-grid" style="--teams:${teamCount()}">${cells.join('')}</div></section>`}
  function normalizeSides(surface){const sides=surface.querySelectorAll('.tb-side');if(sides[0]){sides[0].querySelectorAll('.eyebrow,.tb-section-kicker').forEach(n=>n.remove());const h=sides[0].querySelector('h3');if(h)h.textContent='Alternate Paths'}if(sides[1]){sides[1].querySelectorAll('.eyebrow,.tb-section-kicker').forEach(n=>n.remove());const h=sides[1].querySelector('h3');if(h)h.textContent='Likely Available / Next Pick'}surface.querySelectorAll('.tb-support-card').forEach(card=>{const el=[...card.querySelectorAll('b,strong,h4')].find(x=>x.textContent.trim().split(/\s+/).length>1);if(el&&!el.dataset.v31){el.dataset.v31='1';const[f,l]=splitName(el.textContent);el.innerHTML=`<span>${esc(f)}</span>${l?`<span>${esc(l)}</span>`:''}`;el.classList.add('tbv31-side-name')}})}
  function wire(surface){surface.querySelector('.tbv3-settings,.tbv31-settings')?.addEventListener('click',openSettings);surface.querySelectorAll('[data-v3-view]').forEach(btn=>btn.onclick=()=>{document.querySelector(`.tabs .tab[data-view="${btn.dataset.v3View}"]`)?.click();if(btn.dataset.v3View==='board')setTimeout(renderBoard,0)});surface.querySelectorAll('[data-player]').forEach(el=>el.onclick=()=>window.openPlayerDetails?.(decodeURIComponent(el.dataset.player)))}
  function apply(){const surface=document.querySelector('#frontOfficeRoot .tb-command-surface');if(!surface||surface.dataset.v31===VERSION)return false;surface.dataset.v31=VERSION;document.body.classList.add('tbv31-active');surface.querySelector('.tbv3-projected')?.remove();surface.querySelector('.tbv3-header')?.insertAdjacentHTML('afterend',projectedRail());normalizeSides(surface);surface.querySelector('.tb-draft-pulse')?.remove();wire(surface);renderBoard();return true}
  let q=false;function schedule(){if(q)return;q=true;requestAnimationFrame(()=>{q=false;apply()})}function boot(){schedule();const root=document.getElementById('frontOfficeRoot');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.BoardCockpitV31={apply,renderBoard};
})();